# Generated by Django 4.2.3 on 2023-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_t_user_profile_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='investment_range_max',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='investment_range_min',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='earning_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
