# Generated by Django 4.2.3 on 2023-07-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_plan_price_plan_investment_range_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='investment_range_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='investment_range_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
