# Generated by Django 4.2.3 on 2023-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_plan_investment_range_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
