# Generated by Django 4.2.3 on 2023-07-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_investments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='Approved', max_length=10),
        ),
    ]
