# Generated by Django 4.2.3 on 2023-07-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_investments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='earned',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('rejected', 'Rejected')], default='Approved', max_length=10),
        ),
    ]
